--Codigo=12;Direccion=30;correo,descripcion=50

CREATE TABLE REGION(
	REG_CODIGO varchar(12) PRIMARY KEY,
	REG_NOMBRE varchar(12)
);
---------------------------------------------------------------
CREATE TABLE PATOLOGIA(
	PAT_CODIGO VARCHAR(12) PRIMARY KEY,
	PAT_DESCRIPCION VARCHAR(50)
);
---------------------------------------------------------------
CREATE TABLE EMPRESA(
	EMP_CODIGO VARCHAR(12) PRIMARY KEY,
	EMP_DESCRIPCION VARCHAR(50)
);
---------------------------------------------------------------
CREATE TABLE ESTADO(
	EST_CODIGO VARCHAR (12) PRIMARY KEY,
	EST_DESCRIPCION VARCHAR (50)
)
---------------------------------------------------------------
CREATE TABLE PROFESION(
	PROF_CODIGO VARCHAR(12) PRIMARY KEY,
	PROF_NOMBRE VARCHAR(20)
);
---------------------------------------------------------------
CREATE TABLE ESPECIALIDAD(
	ESP_CODIGO VARCHAR(12) PRIMARY KEY,
	ESP_NOMBRE VARCHAR(20)
);
---------------------------------------------------------------
CREATE TABLE CURSO(
	CUR_CODIGO VARCHAR(12) PRIMARY KEY,
	CUR_DESCRIPCION VARCHAR(50),
	CUR_VALOR_SESION VARCHAR(12),
	CUR_DURACION VARCHAR(12),
	CUR_NUM_SESIONES VARCHAR(12),
	CUR_FECHA_INICIO DATE,
	CUR_FECHA_TERMINO DATE
);
---------------------------------------------------------------
CREATE TABLE SALON(
	SAL_CODIGO VARCHAR(12) PRIMARY KEY,
	SAL_NOMBRE VARCHAR(20),
	SAL_CAPACIDAD VARCHAR(12)
);
---------------------------------------------------------------
CREATE TABLE PROGRAMA(
	PRO_CODIGO VARCHAR(12) PRIMARY KEY,
	PRO_DESCRIPCION VARCHAR(50),
	PRO_VALOR_SESION INTEGER,
	PRO_DURACION VARCHAR(12)
);
---------------------------------------------------------------
CREATE TABLE EVENTO(
	EVE_CODIGO VARCHAR(12) PRIMARY KEY,
	EVE_DESCRIPCION VARCHAR(50),
	EVE_HORA_INICIO VARCHAR(20),
	EVE_HORA_FIN VARCHAR(20),
	EVE_VALOR_ARRIENDO INTEGER,
	EVE_MODALIDAD_PAGO VARCHAR(20),
	EVE_FECHA_PAGO DATE,
	FOREIGN KEY (CLI_RUT) REFERENCES CLIENTE
);
---------------------------------------------------------------
CREATE TABLE CLIENTE(
	CLI_RUT VARCHAR(12) PRIMARY KEY,
	CLI_NOMBRES VARCHAR(30),
	CLI_APELLIDOS VARCHAR(30),
	CLI_TELEFONO INTEGER,
	CLI_DIRECCION VARCHAR(50),
	CLI_ESTADO_CIVIL VARCHAR(30),
	CLI_CORREO_ELECTRONICO VARCHAR (50),
	FOREIGN KEY (COM_CODIGO) REFERENCES COMUNA
);
---------------------------------------------------------------
CREATE TABLE COMUNA(
	COM_CODIGO VARCHAR(12) PRIMARY KEY,
	COM_NOMBRE VARCHAR(20),
	FOREIGN KEY (REG_CODIGO) REFERENCES REGION
);
---------------------------------------------------------------
CREATE TABLE POSEE(
	FECHA_INICIO DATE ,
	FECHA_TERMINO DATE,
	PRIMARY KEY (EST_CODIGO,FECHA_INICIO,CLI_RUT),
	FOREIGN KEY (EST_CODIGO) REFERENCES ESTADO,
	FOREIGN KEY (CLI_RUT) REFERENCES CLIENTE
);
---------------------------------------------------------------
CREATE TABLE TRABAJA(
	PRIMARY KEY(EMP_CODIGO,CLI_RUT),
	FOREIGN KEY(EMP_CODIGO) REFERENCES EMPRESA,
	FOREIGN KEY(CLI_RUT) REFERENCES CLIENTE
);
---------------------------------------------------------------
CREATE TABLE PADECE(
	PRIMARY KEY(PAT_CODIGO, CLI_RUT),
	FOREIGN KEY(PAT_CODIGO) REFERENCES PATOLOGIA,
	FOREIGN KEY(CLI_RUT) REFERENCES CLIENTE
);
---------------------------------------------------------------
CREATE TABLE SESION(
	SES_CODIGO VARCHAR(12) PRIMARY KEY,
	SES_DESCRIPCION VARCHAR(50),
	SES_FECHA DATE,
	SES_HORA VARCHAR(20),
	FOREIGN KEY(SAL_CODIGO) REFERENCES SALON,
	FOREIGN KEY(INS_RUT) REFERENCES INSTRUCTOR
);
---------------------------------------------------------------
CREATE TABLE INSTRUCTOR(
	INS_RUT VARCHAR(12) PRIMARY KEY,
	INS_NOMBRES VARCHAR(30),
	INS_APELLIDOS VARCHAR(30),
	INS_TELEFONO INTEGER,
	INS_DIRECCION VARCHAR(50),
	INS_SUELDO_BASE INTEGER
	FOREIGN KEY(PROF_CODIGO) REFERENCES PROFESION
);








